name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-browser:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/explorama/images/build-image:latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: .m2/repository
        key: "m2-${{ hashFiles('bundles/browser/project.clj') }}"
    - name: Run tests
      run: cd bundles/browser && make test
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: 'bundles/browser/target/coverage/cobertura.xml'
        badge: true
        format: 'markdown'
        output: 'file'
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
  test-electron:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/explorama/images/build-image:latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: .m2/repository
        key: "m2-${{ hashFiles('bundles/electron/project.clj') }}"
    - name: Run tests
      run: cd bundles/electron && make test
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: 'bundles/electron/target/coverage/cobertura.xml'
        badge: true
        format: 'markdown'
        output: 'file'
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY